---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-port
  type: ClusterIP
  selector:
    app: api-gateway
