apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dev-
commonLabels:
  stage: dev
images:
- name: docker.kw01/email-service
  newTag: dev-240517-061406-613c802d