---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  ports:
    - port: 8761
      targetPort: 8761
      name: http-port
  type: ClusterIP
  selector:
    app: eureka-server
