apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dev-
commonLabels:
  stage: dev
images:
- name: docker.kw01/eureka-server
  newTag: dev-240517-044632-d9091d9d
