---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec9
  ports:
    - port: 8080
      targetPort: 8090
      name: http-port
  type: ClusterIP
  selector:
    app: user-service
