apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dev-
commonLabels:
  stage: dev
images:
- name: docker.kw01/user-service
  newTag: dev-240517-235411-e36b23af
