---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-port
  type: ClusterIP
  selector:
    app: movie-service
