apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dev-
commonLabels:
  stage: dev
images:
- name: docker.kw01/api-gateway
  newTag: dev-240517-043805-61578767