apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka-svc
  namespace: kafka
spec:
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: external
      port: 29092
      targetPort: 9092  
  selector:
    service: kafka