apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/kafka-network: "true"
        service: kafka
    spec:
      enableServiceLinks: false
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: bitnami/kafka
        ports:
          - containerPort: 29092
          # - containerPort: 9092
        env:
          # - name: KAFKA_ADVERTISED_LISTENERS
          #   value: "INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:30092"
          # - name: KAFKA_LISTENERS
          #   value: "EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092"
          # - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          #   value: "INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT"

          - name: MY_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ADVERTISED_LISTENERS
            # value: "INTERNAL://$(MY_POD_IP):29092,LISTENER_EXTERNAL://127.0.0.1:30092"
            value: "INTERNAL://$(MY_POD_IP):29092,LISTENER_EXTERNAL://$(MY_HOST_IP):30092"
          - name: KAFKA_LISTENERS
            value: "LISTENER_EXTERNAL://:29092,INTERNAL://:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"

          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "INTERNAL"

          - name: KAFKA_PORT
            value: "9092"

          # - name: KAFKA_ADVERTISED_HOST_NAME
          #   value: "kafka"
          # - name: KAFKA_ADVERTISED_PORT
          #   value: "9092, 29092"  
          # - name: ALLOW_PLAINTEXT_LISTENER
          #   value: "yes"

          - name: KAFKA_BROKER_ID
            value: "1"
          # - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          #   value: "true"            
          # - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          #   value: "1"
          # - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          #   value: "1"          
          - name: KAFKA_NUM_PARTITIONS
            value: "1"
          - name: KAFKA_LOG_CLEANUP_POLICY
            value: "compact"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
        volumeMounts:
          - mountPath: /var/lib/kafka/data
            name: kafka-data
      # hostname: kafka
      restartPolicy: Always
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data-pvc