apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cine-nginx
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: "backend.docker.local"
    http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: dev-api-gateway
            port:
              number: 8080