apiVersion: v1
kind: Service
metadata:
  name: postgres-node
  namespace: postgres
spec:
  selector:
    app.kubernetes.io/name: postgresql
  ports:
    - name: external
      port: 5432
      targetPort: 5432
      nodePort: 30110
      protocol: TCP
  type: NodePort